### Pipeline, step by step

In [216]:
import sys
import os
sys.path.append(os.getcwd())

import logging
import pandas as pd
from data_pipelines.scrapers.filmladder import FilmladderScraper
from data_pipelines.scrapers.imdb import IMDBFetcher, ReferralFetcher
from data_pipelines.daily_pipeline import extract_unique_movies, get_new_movies
from data_pipelines.daily_pipeline import process_cinemas, process_screenings, process_enriched_movies
from backend.data_models.save_to_db import save_all_to_db

pd.options.display.max_rows = 100
pd.set_option('display.max_colwidth', None)
%load_ext autoreload
%autoreload 2

logging.basicConfig(level=logging.INFO)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### Collect screenings

In [172]:
logging.info("Starting daily data pipeline...")

# 1️⃣ Scrape Filmladder (returns two DataFrames)
filmladder = FilmladderScraper()
screenings_df, cinemas_df = filmladder.run()

INFO:root:Starting daily data pipeline...
INFO:WDM:====== WebDriver manager ======
INFO:WDM:Get LATEST chromedriver version for google-chrome
INFO:WDM:Get LATEST chromedriver version for google-chrome
INFO:WDM:Driver [/Users/ardsnijders/.wdm/drivers/chromedriver/mac64/134.0.6998.88/chromedriver-mac-x64/chromedriver] found in cache

### Remove duplicate screenings and process cinemas

In [174]:
# 2️⃣ Remove duplicates (imax, 2d, etc), add unique ids
screenings_df = process_screenings(screenings_df)
cinemas_df = process_cinemas(cinemas_df)

### Fetch ticket destination url

In [223]:
referral_fetcher = ReferralFetcher()
screenings_with_referrals = await referral_fetcher.run(screenings_df[:10])

[autoreload of data_pipelines.scrapers.imdb failed: Traceback (most recent call last):
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 500, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 397, in update_generic
    update(a, b)
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 365, in update_class
    update_instances(old, new)
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 323, in update_instances
    object.__setattr__(ref, "__class__", new)
TypeError: __class__ assignment: 'IMDBFetcher' object layout differs from 'IMDBFetcher'
]

In [221]:
screenings_with_referrals

  fl_cinema_name                 fl_title fl_year          fl_show_datetime                                  fl_ticket_url fl_rating                                                                fl_movie_link                                                                                          fl_poster_url fl_cinema_id                                                    redirect_url
0    bijlmerbios  all we imagine as light    2024 2025-03-14 19:45:00+01:00  https://www.filmladder.nl/kaartjes/1209144794      7.1★  https://www.filmladder.nl/film/all-we-imagine-as-light-2024/popup/amsterdam  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/233/1055233/small_c206909efbc087ff.jpg   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757918/redirect
1    bijlmerbios  all we imagine as light    2024 2025-03-16 15:30:00+01:00  https://www.filmladder.nl/kaartjes/1209145117      7.1★  https://www.filmladder.nl/film/all-we-imagine-as-light-2024/popup/amsterdam  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/233/1055233/small_c206909efbc087ff.jpg   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757919/redirect
2    bijlmerbios              hard truths    2024 2025-03-13 19:45:00+01:00  https://www.filmladder.nl/kaartjes/1209144591      7.3★              https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757916/redirect
3    bijlmerbios              hard truths    2024 2025-03-15 19:00:00+01:00  https://www.filmladder.nl/kaartjes/1209144960      7.3★              https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757920/redirect
4    bijlmerbios                    maria    2017 2025-03-15 21:00:00+01:00  https://www.filmladder.nl/kaartjes/1209144999      7.2★          https://www.filmladder.nl/film/maria-by-callas-2017/popup/amsterdam   https://assets.filmladder.nl/uploads/depot_image/asset/000/913/212/913212/small_37d5aa984717e1f4.jpg   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757917/redirect
5    bijlmerbios                    maria    2017 2025-03-19 19:45:00+01:00  https://www.filmladder.nl/kaartjes/1209183148      7.2★          https://www.filmladder.nl/film/maria-by-callas-2017/popup/amsterdam   https://assets.filmladder.nl/uploads/depot_image/asset/000/913/212/913212/small_37d5aa984717e1f4.jpg   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757663/redirect
6     cinecenter       a complete unknown    2024 2025-03-13 13:45:00+01:00  https://www.filmladder.nl/kaartjes/1209015190      7.4★       https://www.filmladder.nl/film/a-complete-unknown-2024/popup/amsterdam  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2754082/redirect
7     cinecenter       a complete unknown    2024 2025-03-13 20:40:00+01:00  https://www.filmladder.nl/kaartjes/1209223989      7.4★       https://www.filmladder.nl/film/a-complete-unknown-2024/popup/amsterdam  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2761583/redirect
8     cinecenter       a complete unknown    2024 2025-03-14 13:45:00+01:00  https://www.filmladder.nl/kaartjes/1209224169      7.4★       https://www.filmladder.nl/film/a-complete-unknown-2024/popup/amsterdam  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2761660/redirect
9     cinecenter       a complete unknown    2024 2025-03-14 20:45:00+01:00  https://www.filmladder.nl/kaartjes/1209224311      7.4★       https://www.filmladder.nl/film/a-complete-unknown-2024/popup/amsterdam  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2761652/redirect

### Extract unique titles from screenings, then visit each page to fetch corresponding IMDB ID

In [176]:
scraped_movies = extract_unique_movies(screenings_df)
scraper = IMDBFetcher()
scraped_movies_with_id = await scraper.run(scraped_movies)
# TODO move this into scraper.run()
# scraped_movies_with_id['imdb_id'] = scraped_movies_with_id['imdb_link'].apply(lambda x: x.split('/')[-1] if x is not None else None)

[autoreload of data_pipelines.scrapers.imdb failed: Traceback (most recent call last):
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 500, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 397, in update_generic
    update(a, b)
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 365, in update_class
    update_instances(old, new)
  File "/Users/ardsnijders/Documents/cineville_scraper/env/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 323, in update_instances
    object.__setattr__(ref, "__class__", new)
TypeError: __class__ assignment: 'IMDBFetcher' object layout differs from 'IMDBFetcher'
]

### Use the fetched IMDB ID as a look up for which titles are not yet in the db and consequently, new

In [177]:
pd.set_option('display.width', 1000)
new_movies = get_new_movies(scraped_movies=scraped_movies_with_id)
new_movies

                                         fl_title fl_year                                                                                  fl_movie_link                              imdb_link     imdb_id
2                                           maria    2017                            https://www.filmladder.nl/film/maria-by-callas-2017/popup/amsterdam   https://www.imdb.com/title/tt7364566   tt7364566
16                              crossing istanbul    2024                          https://www.filmladder.nl/film/crossing-istanbul-2024/popup/amsterdam  https://www.imdb.com/title/tt27417166  tt27417166
18                         disney snow white (nl)    2025                       https://www.filmladder.nl/film/disney-snow-white-nl-2025/popup/amsterdam   https://www.imdb.com/title/tt6208148   tt6208148
40                                      half moon    2024                                  https://www.filmladder.nl/film/half-moon-2024/popup/amsterdam  https://www.imdb.com/title/tt35618593  tt35618593
49                              hoe te verdwijnen    2024                          https://www.filmladder.nl/film/hoe-te-verdwijnen-2024/popup/amsterdam  https://www.imdb.com/title/tt34224914  tt34224914
92                                          manas    2024                                      https://www.filmladder.nl/film/manas-2024/popup/amsterdam  https://www.imdb.com/title/tt27911420  tt27911420
118  hans zimmer & friends: diamond in the desert    2025  https://www.filmladder.nl/film/hans-zimmer-friends-diamond-in-the-desert-2025/popup/amsterdam  https://www.imdb.com/title/tt35616060  tt35616060
126                       small things like these    2024                    https://www.filmladder.nl/film/small-things-like-these-2024/popup/amsterdam  https://www.imdb.com/title/tt27196021  tt27196021
138                                    the return    2024                                 https://www.filmladder.nl/film/the-return-2024/popup/amsterdam  https://www.imdb.com/title/tt19861162  tt19861162
146                                     inception    2010                                  https://www.filmladder.nl/film/inception-2010/popup/amsterdam   https://www.imdb.com/title/tt1375666   tt1375666

### Get identifiers from Letterboxd (lb_id, tmdb_id, lb_film_slug)

In [178]:
# The following function visits the letterboxd page for each new film in the db and retrieves the lb slug and the TMDB id
from data_pipelines.scrapers.imdb import LetterboxdFetcher
lb_scraper = LetterboxdFetcher()
new_movies_with_lb = await lb_scraper.run(new_movies)

/Users/ardsnijders/Documents/cineville_scraper/backend/data_pipelines/scrapers/imdb.py:174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Collect Metadata from TMDB using tmdb_id (movie_info, movie_keywords, movie_reviews)

In [179]:
from data_pipelines.tmdb import collect_metadata
movies_with_metadata = collect_metadata(new_movies_with_lb)

### TODO: Embed metadata for new titles

In [ ]:
from vector_search.vector_search import MovieEmbedder
embedding_model = MovieEmbedder
movies_with_embeddings = embedding_model(movies_with_metadata)

### TODO: Fetch ratings for underrated titles if applicable

In [ ]:
raise NotImplementedError

### TODO: Save to PostgreSQL DB

In [11]:
# enriched_new_movies = enriched_new_movies.where(pd.notna(enriched_new_movies), None)
save_all_to_db(cinemas_df=cinemas_df,
               movies_df=enriched_new_movies,
               screenings_df=screenings_df)